version: "3.9"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - DISCORD_TOKEN=123
      - STATCORD_KEY=123
      - DATABASE_URL=mysql+pymysql://root:password@db:3306/db
      - TMDB_API_KEY=123
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
  # Names our volume
volumes:
  my-db:



