name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build container image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/peribot
        tag_with_sha: true
        tag_with_ref: true
